name: Add a new model

# Trigger the workflow on pull request
on:
  issues:
    types: [assigned]

jobs:
  create_new_branch:
    if: ${{startsWith(github.event.issue.title, 'New Model:')}}

    runs-on: ubuntu-latest

    outputs:
      BRANCHNAME: ${{ steps.branch.outputs.branchName }}

    steps:
      # Checkout the repository to the GitHub Actions runner
      - uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/addModel.yml # optional but recommended

      - name: Get Python Scripts
        id: python_scripts
        run: |
          echo "pythons<<EOF" >> $GITHUB_ENV
          echo "${{ steps.issue-parser.outputs.issueparser_python-scripts }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Get the Path
        id: get_path
        run: echo "path=${{ steps.issue-parser.outputs.issueparser_path }}" >> $GITHUB_OUTPUT

      # This will automatically create a new branch from this issue, using custom config at /.github/issue-branch.yml
      - name: Create Issue Branch
        id: branch
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN:
            ${{ secrets.GITHUB_TOKEN }}

      - name: Install svn
        run: sudo apt-get install subversion

      # Checkout the repository to the GitHub Actions runner to the new branch created for the issue
      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.branch.outputs.branchName }}
    
    
      - name: Clone python scripts
        run: |
          python_scripts="${{ env.pythons }}"
          # Split the URLs into a list
          IFS=$'\n' read -rd '' -a urls <<< "$python_scripts"
          
          # Loop through each URL
          for url in "${urls[@]}"; do
            # Replace /tree/branchName or /blob/branchName with /trunk
            svn_url=$(echo "$url" | sed -E 's|/tree/[^/]+|/trunk|; s|/blob/[^/]+|/trunk|')
          
            # Perform svn export
            svn export $svn_url "./${{ steps.get_path.outputs.path }}"
          done