name: Add a new model

# Trigger the workflow on pull request
on:
  issues:
    types: [assigned]

jobs:
  create_new_branch:
    if: ${{startsWith(github.event.issue.title, 'New Model:')}}

    runs-on: ubuntu-latest

    outputs:
      BRANCHNAME: ${{ steps.branch.outputs.branchName }}
      PYTHONS: ${{ env.pythons2 }}

    steps:
      # Checkout the repository to the GitHub Actions runner
      - uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/addModel.yml # optional but recommended

      - name: Get Python Scripts
        id: python_scripts
        run: |
          echo "pythons<<EOF" >> $GITHUB_ENV
          echo "${{ steps.issue-parser.outputs.issueparser_python-scripts }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Get the Path
        id: get_path
        run: echo "path=${{ steps.issue-parser.outputs.issueparser_path }}" >> $GITHUB_OUTPUT

      # Get docker url
      - name: Get Docker URL
        id: get_docker_url
        run: echo "docker_url=${{ steps.issue-parser.outputs.issueparser_docker }}" >> $GITHUB_OUTPUT

      # This will automatically create a new branch from this issue, using custom config at /.github/issue-branch.yml
      - name: Create Issue Branch
        id: branch
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN:
            ${{ secrets.GITHUB_TOKEN }}

      - name: Install svn
        run: sudo apt-get install subversion

      # Checkout the repository to the GitHub Actions runner to the new branch created for the issue
      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.branch.outputs.branchName }}
    
      - name: Generate SVN URLs
        id: generate_urls
        run: |
          echo "pythons2<<EOF" >> $GITHUB_ENV
          python ./.github/workflows/getPythonScripts.py >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        env:
            pythons: ${{ env.pythons }}
        
      - name: Clone python scripts
        run: |
          svn_urls="${{ env.pythons2 }}"
          for svn_url in $svn_urls; do
            svn export --force $svn_url ./${{ steps.get_path.outputs.path }}
          done

      - name: Clone docker folder
        run: |
          url="${{ steps.get_docker_url.outputs.docker_url }}"
          echo $url
          svn_url=$(echo "$url" | sed -E 's|/tree/[^/]+|/trunk|; s|/blob/[^/]+|/trunk|')

          svn export --force $svn_url ./${{ steps.get_path.outputs.path }}

      # Commit the new created files and folders to the branch needs.create_new_branch.outputs.BRANCHNAME
      - name: Commit the new files
        run: |
          git config --global user.name "trained_models"
          git config --global user.email "trained_models"
          git add ./${{ steps.get_path.outputs.path }}
          git commit -m "Added model files"
          git pull --rebase origin main
          git push

  test_env_vars:
    runs-on: ubuntu-latest
    needs: create_new_branch
    
    steps:
    
    - uses: actions/checkout@v3

    - name: Get the Path
      id: get_path
      run: echo "${{ needs.create_new_branch.outputs.PYTHONS }}"